name: Tests

on:
  pull_request:

jobs:
  go-guard:
    uses: ./.github/workflows/go_guard.yml

  tests:
    needs: go-guard
    if: needs.go-guard.outputs.go_mod_exists == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run unit tests
        run: |
          make unit-test
      - name: Run integration tests
        run: |
          make integration-test
      - name: Check coverage
        run: |
          source .github/ci.env
          make coverage
